In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
from sklearn.preprocessing import LabelEncoder

In [37]:
data = pd.read_csv("glass.csv")

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [39]:
i = data.iloc [:,:9]
d = data.iloc [:,9]

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (i, d, test_size = .30,random_state=0)

In [41]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [42]:
model.predict(x_test)

array([7, 1, 1, 6, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 7, 1, 1, 1, 1, 2, 3,
       7, 7, 1, 1, 7, 1, 1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 7, 5, 6, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 7, 1, 1, 1, 1, 1, 7, 1, 1, 1, 1, 2, 1],
      dtype=int64)

In [43]:
model.score(x_test,y_test)

0.46153846153846156

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
clf = MultinomialNB()
clf.fit(i,d)

MultinomialNB()

In [46]:
clf.predict(x_test)

array([7, 2, 2, 2, 7, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 7, 1, 2, 1, 2, 5, 2,
       7, 7, 2, 1, 7, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 7, 7, 2, 2, 1,
       1, 1, 1, 2, 2, 2, 1, 7, 7, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2],
      dtype=int64)

In [47]:
clf.score(x_test,y_test)

0.5230769230769231

In [48]:
from sklearn.naive_bayes import BernoulliNB

In [49]:
bnb= BernoulliNB()

In [50]:
bnb.fit(i,d)

BernoulliNB()

In [51]:
bnb.predict(x_test)

array([7, 1, 2, 6, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 7, 1, 2, 1, 1, 2, 2,
       7, 2, 2, 1, 7, 1, 1, 2, 1, 6, 1, 2, 2, 2, 2, 1, 2, 7, 7, 6, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 2, 7, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2],
      dtype=int64)

In [52]:
bnb.score(x_test,y_test)

0.5230769230769231